### PR TITLE
fix(backend): route application logs to stdout with trace-id correlation

### PR DESCRIPTION
**Pull request by Geoffe-Ga**
## Problem

Application logs (including the startup-seed diagnostics needed to investigate why the production database has 0 `StageContent` rows) never appear in Railway logs. Python's root logger ships with no handlers, so every `logger.info(...)` in the app is silently dropped, while Uvicorn's separately-configured access logs still show up — making the app look healthy while its own telemetry is invisible.

## Solution

- **`observability.configure_stdout_logging()`** (new) — installs a single `StreamHandler` writing to stdout at INFO level on the root logger at `main` import time, with `TraceIdLogFilter` attached **to the handler** and a `%(trace_id)s`-aware formatter. Idempotent and deferential: any environment that already configured root handlers (pytest, custom deployments) is left untouched.
- **Handler-level (not logger-level) filter** — logger-level filters are skipped for records propagating up from named child loggers (`logging.getLogger(__name__)`, used everywhere in this codebase), which is exactly the `KeyError` → `--- Logging error ---` failure mode caught in review round 2. The old logger-level attachment (`install_trace_id_logging()`) is removed entirely, so the filter now lives in a single, clear place — addressing review round 3's redundancy note.
- **End-to-end regression test** — `test_child_logger_record_renders_trace_id_through_configured_handler` logs through a *named child logger* and asserts the rendered stdout line carries the trace id with no logging error, closing the test gap review round 3 flagged (presence-only assertions could not catch the propagation bug).
- **Seed instrumentation** — `startup_seed_begin` / `database_session_created` / `startup_seed_complete` / `startup_seed_skipped` markers in the lifespan hook so the next deploy's boot log shows exactly where seeding stops.

## Bonus fix: jest worker crash on every full frontend run

`MapScreenColdStart.test.tsx` mounted `MapScreen` (which arms `Animated` timing loops) without fake timers or an unmount. The leaked timers fire after Jest tears the environment down; `Easing.bezier` then lazy-imports against the destroyed module registry and the uncaught `TypeError: _bezier is not a function` **kills the worker process** — surfacing as `Jest worker encountered 4 child process exceptions` on full-suite runs while the file passes in isolation by winning the race. This deterministically broke Gate 2 (pre-push) runs. Fixed with fake timers + `afterEach` unmount, mirroring `MapScreen.test.tsx`'s teardown hygiene.

## Scope note (history rewrite)

Earlier revisions of this branch also carried the proportional drip-calendar-lock feature — that work **already landed on main** as `0029526` (byte-identical content), so this branch was rebuilt on top of current main carrying only the logging work. This removes ~350 lines of duplicate diff and, more importantly, stops this PR from silently reverting newer main work its stale base predated (the `ensure_aware` tz-normalization refactor from #1478, its three regression tests, and the reflections/promotions router mounts).

## Verification

- Full backend suite: 96.72% coverage (≥ 90% gate)
- Full frontend suite: 385/385 suites, 4039 tests, coverage gate met
- `pre-commit run --all-files` passes; full pre-push gate (xenon, radon, both coverage suites) passed on push
- New tests pin: handler/filter/level installation, pre-configured-environment no-op, default-root inspection, and the full child-logger → handler → formatter → stdout pipeline

## Next steps

Once deployed, the boot log will show the seed markers (`startup_seed_begin` → `seed_complete inserted=N` per seeder → `startup_seed_complete`, all trace-id-correlated), which will pinpoint why production has 0 `StageContent` rows.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01981WayW61ANymxRaNQUfxV

### CODE REVIEW

**Comment by Geoffe-Ga** [comment]
@claude please review

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by Geoffe-Ga** [comment]
Thanks for the thorough review! I've addressed your suggestion about the trace_id formatter.

**Addressed:**
- ✅ Updated the root logger formatter to include `%(trace_id)s` so request correlation IDs rendered in stdout logs (commit `646f0a17`)

**Noted for future:**
- 📝 Will split feature PRs atomically in the future — the proportional drip-calendar-lock feature should have been in a separate PR from the logging fix

The trace_id inclusion is a real improvement that connects the existing `TraceIdLogFilter` infrastructure to the new stdout logs, enabling proper request correlation in production without needing indirect correlation keys.

All tests pass locally and CI is green. Ready to merge when you confirm.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by Geoffe-Ga** [comment]
@claude please re-review

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by Geoffe-Ga** [comment]
Thanks for catching that critical bug! You're absolutely right — attaching the filter to the logger instead of the handler meant it never ran for child-logger records propagating through the root's handlers.

**Fixed in commit `d1fe429b`:**
- Moved `TraceIdLogFilter` attachment from the root logger to the StreamHandler itself
- Added explanatory comment about Python's logging filter propagation semantics
- Handler-level filters now apply to ALL records reaching the handler, regardless of origin logger

This ensures child loggers (like `logging.getLogger(__name__)` used throughout the codebase) have their `trace_id` properly injected before the formatter tries to interpolate `%(trace_id)s`.

✅ All 13 lifespan tests pass
✅ All pre-commit hooks pass
✅ Ready for re-review and merge

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by Geoffe-Ga** [comment]
@claude please re-review

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by Geoffe-Ga** [comment]
@claude please re-review

The branch was rebuilt on top of current main — the drip-calendar-lock feature you reviewed in rounds 1–3 already landed on main as `0029526` (byte-identical), so it has been dropped from this branch to avoid duplicate history and to stop the stale base from reverting newer main work (#1478's `ensure_aware` refactor, its regression tests, and the reflections/promotions router mounts).

What remains, incorporating both of your round-3 follow-ups:
- `configure_stdout_logging()` replaces `install_trace_id_logging()` — the `TraceIdLogFilter` now lives in exactly one place, on the handler (your redundancy note).
- An end-to-end regression test that logs through a named child logger and asserts the rendered stdout line carries the trace id (your test-gap note).
- A `test(map)` commit fixing a leaked-`Animated`-timer bug in `MapScreenColdStart.test.tsx` that was killing jest workers on every full-suite run (pre-existing on main; it blocked this branch's pre-push gate).

---
_Generated by [Claude Code](https://claude.ai/code/session_01981WayW61ANymxRaNQUfxV)_

---
_Generated by [Claude Code](https://claude.ai/code)_
